### ISSUE TITLE
Info Signs

### ISSUE THREAD

**Issue by Ayymoss** [RedTech64/HyperConomyX#2]
Info Signs just seem to be straight-up broken...

https://i.imgur.com/535ktdO.png

No errors, nothing. Just doesn't do anything.

Followed the tutorial by the original creator: https://www.youtube.com/watch?v=8vimUcLkfDg

This is reinforced by the fact if I type /repairsigns 10 10 10 stood on top of the sign it says "No Signs Found".

**Comment by Ayymoss** [comment]
Item Frame's also don't work, no error. Just no behaviour at all.

**Comment by coleweinman** [comment]
@MrAmos123 
Info Signs have actually be redesigned in this version. I will be creating a page soon with more information, but for now the format is the following:

Line 1 - Sign type ("BUY" or "SELL", etc)
Line 2 - Object name
Line 3 - Object name continued

Sorry for the late response!
